### ISSUE TITLE
Close TapDance connection correctly

### ISSUE THREAD

**Issue by ewust** [SergeyFrolov/gotapdance#12]
Instead of waiting for a round-trip of RSTs from the decoy server, we need to have the client time-out each decoy connection BEFORE the decoy is going to try to tear down the connection. In other words, each decoy connection should timeout after a short period (~20 seconds), and then reconnect (create a new decoy connection with the same connection ID).

**Comment by SergeyFrolov** [comment]
Current logic is that we reconnect when connection is closed by decoy, which clearly looks suspicious on the wire:

1. Decoy times out and sends FIN
2. Client ignores FIN due to incorrect SEQ
3. Client sends more stuff
4. Decoy responds to more stuff with RST
5. Client doesn't ignore RST and closes connection
6. Client reconnects.

The question is: after implementing this timeout, do we still reconnect upon aforementioned conditions or tear Client <-> Covert connection down?
If we fail to timeout in time for any reason, then observable events 1-5 still will happen, might just as well keep reconnecting.
On the other hand, this calls for better handling of timeout and observability, e.g. we want to make the event of us not timing out so rare, that it stops mattering. But will we be able to get that?

**Comment by SergeyFrolov** [comment]
Timeout added in 7dfb4699c459ddd00bd34bb329f72ba4188c82e2
We do not reconnect if decoy tears connection down
