### ISSUE TITLE
Client abruptly drops HTTPS flows that aren't picked up by the station

### ISSUE THREAD

**Issue by SalmonProject** [sergeyfrolov/gotapdance#38]
In testing one of my changes, Dan noticed that when the station doesn't pick up a tag, the client drops the HTTPS session hard, with RSTs being sent in response to whatever the decoy sends. This might need to be a wishlist feature, but it would be good if in case of station-non-pickup, the client ended the X-Ignore field and let the decoy respond to a (relatively) ordinary HTTP request.

**Comment by sergeyfrolov** [comment]
This issue is non-trivial to fix, client sending 2 requests in a raw is going to look weird. Worst of all, if client sends FIN after incomplete request, decoy decides to respond with appdata (Y U DO DIS APACHE???), but connection is closed according to client, so it responds with RST, which gets echoed back.

1. Generate ascii-range message with same length as tdRequest, that ends with "/r/n/r/n", send it and forget(don't close!). On the wire this will look like spurious retransmission. Which doesn't seem to be very frequent event in the wild.
2. Generate ascii-range message with random length, that ends with "/r/n/r/n", send it and forget(don't close!). Weird, since clients don't generally send 2 messages in a row.
3. Send TLS CloseNotify.  Same weird stuff with appdata happens.
4. Just forget about connection: let it naturally timeout _by station_. Same weird stuff with appdata happens, but much later.

None of the solutions above are perfect, I was debating between 2nd and 4th and chose 2nd. This provides kinda ok protection against censors, who can't observe both directions.
