### ISSUE TITLE
Pre-built binary?

### ISSUE THREAD

**Issue by testcaoy7** [sergeyfrolov/gotapdance#50]
Please release pre-built binary files for Windows, macOS and Linux.

Easy distribution of this software is vital for anti-censorship.

**Comment by sergeyfrolov** [comment]
Thanks for your interest in this project! In order to answer this request, I will first have to mention a few things about what TapDance is today.
Recently, we have had a [trial](https://www.usenix.org/system/files/conference/foci17/foci17-paper-frolov_0.pdf), in which we partnered with [Psiphon](https://psiphon.ca/index.html) and acted _as a transport_ for their users. Given the nature of TapDance technology, innovative part of which is the unblockable transport itself, it makes sense for us to heavily prioritize development of the transport and let others act as a "frontend". 
For that reason, at this time, we don't really have a good GUI client for various platforms. That being said,
1. We do intend to start building our own client software in future.
2. I can build command line clients for these platforms, which would spin up SOCKS tunnel,  but I would be against distributing it. It's not easy to use and it does not have auto-update functionality, which is **critical** for your security and safety. So this would be for research/testing purposes.

For your personal use, I will recommend you to simply download [Psiphon](https://psiphon.ca/en/download.html?10Years). I will keep this issue open, and you will be notified when we have a good client for those platforms.

**Comment by testcaoy7** [comment]
@sergeyfrolov I appreciate your candour. The recent trend of Chinese citizen to bypass censorship is to rent a virtual private server (VPS). Due to economic reason, these VPS are usually low-end and running Linux with only command line interface. In the future, it would be nice that if you can release a TapDance server as well as a client. Thank you for your hard work!

**Comment by sergeyfrolov** [comment]
You don't have to run your own VPS in order to enter the refraction network.
To understand how this works, you may take a look at diagram at https://refraction.network - ISP partner will be your exit node.
What you've seen in ClientConf is [protobuf](https://developers.google.com/protocol-buffers) with list of Reachable Sites.
So, you can use the client as SOCKS proxy for **testing** purposes for free. But, again, it will be unstable and not suitable for real-world use.
