### ISSUE TITLE
Wishlist: a test decoy mode

### ISSUE THREAD

**Issue by nikitaborisov** [sergeyfrolov/gotapdance#65]
When testing a single decoy, the following behavior would be useful:
1. Automatically dial that decoy, without waiting for a connection to the proxy socket
2. Only dial that decoy once, rather than keep retrying upon failure
3. Exit after the connection fails or succeeds
4. Print a final error message documenting failure reason, or success, before exiting

This would make it much easier to test an individual decoy and also aggregate failure reports. 

I'll assign this to me since it's closely tied to the auto-placement scripts but I'm happy to have help from @sergeyfrolov

**Comment by nikitaborisov** [comment]
Nvm I can't assign issues here.

**Comment by sergeyfrolov** [comment]
I think best way to do this would be not to get a separate program for this, and not try to integrate it with cli. You'd be able to test as many decoy as you want with lightweight goroutines, rather than spawning processes. Assuming that's the path we'd take, we can achieve this by adding a function to `gotapdance` that would look something like

```
MakeRawTestConn(decoy pb.TLSDecoySpec) *tdRawConn {
   // fill all the fields, like it's done in makeTdRaw and conn_flow.go
   tdRaw.pinDecoySpec = true
   tdRaw.decoySpec = decoy
  return tdRaw
}
```

and then in your tool you would `tdRaw.Dial()` that would give you exact error

That doesn't address #2, which we could solve by using exported constants
```
ConnectionAttemptsOnDial = 6
ConnectionAttemptsOnRedial = 2
```
which you would then override.

**Comment by nikitaborisov** [comment]
Thanks, that sounds like a good approach
