### ISSUE TITLE
Expect MSG_RECONNECT rather than MSG_INIT on reconnects

### ISSUE THREAD

**Issue by SalmonProject** [SergeyFrolov/gotapdance#9]
The client should accept a MSG_RECONNECT when reconnecting. It should probably continue accepting MSG_INITs (at least until all of this is resolved), but should issue some warning or somehow be aware that the station may be treating the reconnect attempt as a new connection.

**Comment by SergeyFrolov** [comment]
I recall us wanting to reserve MSG_RECONNECT for other usage: signal to client that he needs to reconnect for camouflage reasons. However, we can designate new message for it, when the time comes.
I agree that sending something other than INIT on reconnect is the right way. Fixed in 3a8373162b595a200ad720deb700cfd3a2b7cbc9
